version: '20'

services:
  localhost:
    container_name: localhost
    image: mysql:8.0
    # command: --default-authentication-plugin=mysql_native_password
    env_file: ./.env
    restart: always
    ports:
      - 127.0.0.1:${DB_PORT}:3306
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    # volumes: 
    #   - db-config:/etc/mysql
    #   - db-data:/var/lib/mysql
    #   - ./db/backup/files/:/data_backup/data
      tty: true

  ls10_net_server_application:
    # container_name: ls10_net_server_application
    build:
      context: ../ls10_net_web_server/
      dockerfile: Dockerfile
    env_file: ../ls10_net_web_server/.env
    depends_on:
      - localhost
    volumes:
    - '../ls10_net_web_server/${BACKEND_APPLICATION_DIRECTORY}/:/app/www'
    stdin_open: true
    tty: true
    ports:
    - 127.0.0.1:33010:33010
    environment:
      ENV: dev
      DB_HOST: 'localhost'

  ls10_net_router:
    # container_name: ls10_net_router
    build:
      context: ../ls10_net_router
      dockerfile: Dockerfile
    env_file: ../ls10_net_router/.env
    depends_on:
      - localhost
    volumes:
    - '../ls10_net_router/${BACKEND_APPLICATION_DIRECTORY}/:/app/www'
    stdin_open: true
    tty: true
    ports:
    - 127.0.0.1:33002:33002
    environment:
      ENV: dev
      DB_HOST: 'localhost'

  ls10_net_entity:
    # container_name: ls10_net_entity
    build:
      context: ../ls10_net_entity
      dockerfile: Dockerfile
    env_file: ../ls10_net_entity/.env
    depends_on:
      - localhost
      - ls10_net_router
    volumes:
    - '../ls10_net_entity/${BACKEND_APPLICATION_DIRECTORY}/:/app/www'
    stdin_open: true
    tty: true
    ports:
    - 127.0.0.1:33999:33999
    environment:
      ENV: dev
      DB_HOST: 'localhost'

  ls10_net_property:
    # container_name: ls10_net_property
    build:
      context: ../ls10_net_property_service
      dockerfile: Dockerfile
    env_file: ../ls10_net_property_service/.env
    depends_on:
      - localhost
      - ls10_net_router
    volumes:
    - '../ls10_net_property_service/${BACKEND_APPLICATION_DIRECTORY}/:/app/www'
    stdin_open: true
    tty: true
    ports:
    - 127.0.0.1:33003:33003
    environment:
      ENV: dev
      DB_HOST: 'localhost'

  ls10_net_api_gateway:
    # container_name: ls10_net_api_gateway
    build:
      context: ../ls10_net_api_gateway/
      dockerfile: Dockerfile
    env_file: ../ls10_net_api_gateway/.env
    depends_on:
      - localhost
      - ls10_net_router
    volumes:
    - '../ls10_net_api_gateway/${BACKEND_APPLICATION_DIRECTORY}/:/app/www'
    stdin_open: true
    tty: true
    ports:
    - 0.0.0.0:33001:33001
    environment:
      ENV: dev
      DB_HOST: 'localhost'

    # command: >
    #   bash -c "cd /app
    #   && echo install dep
    #   && npm i --verbose
    #   && npm i -g nodemon
    #   && npm run run-build"




