version: '20'

services:
  mysql_application:
    container_name: mysql_application
    image: mysql:8.0
    # command: --default-authentication-plugin=mysql_native_password
    env_file: ./.env
    restart: always
    ports:
      - 127.0.0.1:${DB_PORT}:3306
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    # volumes: 
    #   - db-config:/etc/mysql
    #   - db-data:/var/lib/mysql
    #   - ./db/backup/files/:/data_backup/data
      tty: true

  edumeserver_application:
    # container_name: edumeserver_application
    build:
      context: ../edumeserver/
      dockerfile: Dockerfile
    env_file: ../edumeserver/.env
    depends_on:
      - mysql_application
    volumes:
    - '../edumeserver/${BACKEND_APPLICATION_DIRECTORY}/:/app/www'
    stdin_open: true
    tty: true
    ports:
    - 127.0.0.1:3300:3300
    environment:
      ENV: dev
      DB_HOST: 'mysql_application'

  edume_router:
    # container_name: edume_router
    build:
      context: ../edume_router
      dockerfile: Dockerfile
    env_file: ../edume_router/.env
    depends_on:
      - mysql_application
    volumes:
    - '../edume_router/${BACKEND_APPLICATION_DIRECTORY}/:/app/www'
    stdin_open: true
    tty: true
    ports:
    - 127.0.0.1:33002:33002
    environment:
      ENV: dev
      DB_HOST: 'mysql_application'

  edume_entity:
    # container_name: edume_entity
    build:
      context: ../edume_entity
      dockerfile: Dockerfile
    env_file: ../edume_entity/.env
    depends_on:
      - mysql_application
      - edume_router
    volumes:
    - '../edume_entity/${BACKEND_APPLICATION_DIRECTORY}/:/app/www'
    stdin_open: true
    tty: true
    ports:
    - 127.0.0.1:33999:33999
    environment:
      ENV: dev
      DB_HOST: 'mysql_application'

  edume_property:
    # container_name: edume_property
    build:
      context: ../edume_property_service
      dockerfile: Dockerfile
    env_file: ../edume_property_service/.env
    depends_on:
      - mysql_application
      - edume_router
    volumes:
    - '../edume_property_service/${BACKEND_APPLICATION_DIRECTORY}/:/app/www'
    stdin_open: true
    tty: true
    ports:
    - 127.0.0.1:33003:33003
    environment:
      ENV: dev
      DB_HOST: 'mysql_application'

  edumeapi_gateway:
    # container_name: edumeapi_gateway
    build:
      context: ../edumeapi_gateway/
      dockerfile: Dockerfile
    env_file: ../edumeapi_gateway/.env
    depends_on:
      - mysql_application
      - edume_router
    volumes:
    - '../edumeapi_gateway/${BACKEND_APPLICATION_DIRECTORY}/:/app/www'
    stdin_open: true
    tty: true
    ports:
    - 0.0.0.0:33001:33001
    environment:
      ENV: dev
      DB_HOST: 'mysql_application'

    # command: >
    #   bash -c "cd /app
    #   && echo install dep
    #   && npm i --verbose
    #   && npm i -g nodemon
    #   && npm run run-build"




